---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logbook
  labels:
    app: logbook
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logbook
  template:
    metadata:
      labels:
        app: logbook
        monitoring: "true"
    spec:
      containers:
        - name: logbook
          image: {{ .Values.image.registry }}/{{ .Values.image.owner }}/{{ .Values.images.logbook }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: logbook-api
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "350Mi"
          env:
            - name: TZ
              value: Europe/Berlin

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/logbook_service

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.database.user }}

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD
