---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suggestion
  labels:
    app: suggestion
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suggestion
  template:
    metadata:
      labels:
        app: suggestion
        monitoring: "true"
    spec:
      containers:
        - name: suggestion
          image: {{ .Values.image.registry }}/{{ .Values.image.owner }}/{{ .Values.images.genai }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
              name: suggestion-api
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          env:
            - name: LMSTUDIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm-secret
                  key: LMSTUDIO_API_KEY
            
            - name: LMSTUDIO_MODEL
              value: "openai/gpt-oss-120b"
            
            - name: LMSTUDIO_BASE_URL
              value: "https://logos.aet.cit.tum.de"

            - name: LOGBOOK_BASE_URL
              value: "http://logbook-service/api"
