spring.application.name=logbook-service
server.port=8080
spring.mvc.servlet.path=/api

# hardcoded connection credentials will be overwritten using env vars in production
spring.datasource.url=jdbc:postgresql://localhost:55002/logbook_service
spring.datasource.username=logbook_user
spring.datasource.password=logbook_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
