{{- if .Values.monitoring.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: grafana
          image: {{ .Values.monitoring.grafana.image }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.monitoring.grafana.existingSecret }}
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.monitoring.grafana.existingSecret }}
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_SERVER_ROOT_URL
              value: https://{{ .Values.ingress.host }}/monitoring/grafana/
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
          securityContext:
            runAsUser: 472
            runAsGroup: 472
          ports:
            - containerPort: 3000
              name: grafana-http
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yml
              subPath: datasources.yml
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
              subPath: dashboards.yml
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards/backend-observability.json
              subPath: backend-observability.json
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboards
          configMap:
            name: grafana-dashboards
        - name: data
          persistentVolumeClaim:
            claimName: grafana-pvc
{{- end }}
