{{- if .Values.monitoring.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: prometheus
data:
  application-alerts.yml: |
{{ tpl (.Files.Get "files/prometheus/application-alerts.yml") . | indent 4 }}
{{- end }}
