{{- if .Values.monitoring.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: prometheus-http
{{- end }}
