image:
  registry: ghcr.io
  owner: aet-devops26/team-good-thing-i-like-my-builds-cancelled

images:
  genai: genai-service:main
  route: route-service:main
  logbook: logbook-service:main
  client: client:main

ingress:
  enabled: true
  host: cancelled.stud.k8s.aet.cit.tum.de

database:
  user: logbook_user
  password: logbook_password
