---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cancelled-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"

spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: cancelled-tls
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - pathType: Prefix
            path: "/api/v1/route"
            backend:
              service:
                name: route-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/api/v1/suggestion"
            backend:
              service:
                name: genai-service
                port:
                  number: 8080
          - pathType: Prefix
            path: "/api/v1/logbook"
            backend:
              service:
                name: logbook-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/pgadmin"
            backend:
              service:
                name: pgadmin-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/monitoring/grafana"
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000
          - pathType: Prefix
            path: "/monitoring/prometheus"
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: client-service
                port:
                  number: 80
