---
apiVersion: v1
kind: Service
metadata:
  name: logbook-service
  labels:
    app: logbook
spec:
  selector:
    app: logbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: logbook-api
