---
apiVersion: v1
kind: Service
metadata:
  name: suggestion-service
  namespace: my-namespace
  labels:
    app: suggestion
spec:
  selector:
    app: suggestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: suggestion-api
